=== Cenze94/GGarden/data/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ggarden.com" targetNamespace="http://www.ggarden.com" elementFormDefault="qualified">
	<xsd:element name="prodotti" type="Tprodotti"/>
	
	<xsd:complexType name="Tprodotti">
	<xsd:sequence>
		<xsd:element name="pianta" type="Tpianta" minOccurs="1" maxOccurs="unbounded"/>
		<xsd:element name="attrezzo" type="Tattrezzo" minOccurs="1" maxOccurs="unbounded"/>
	</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Tpianta">
	<xsd:sequence>
		<xsd:element name="nome" type="xsd:string"/>
		<xsd:element name="nome_scientifico" type="xsd:string"/>
		<xsd:element name="tipo" type="xsd:string"/>
		<xsd:element name="prezzo" type="Tprezzo"/>
		<xsd:element name="descrizione" type="xsd:string"/>
		<xsd:element name="dettagli" type="Tdettagli"/>
		<xsd:element name="piantagione" type="xsd:string"/>
		<xsd:element name="cura" type="xsd:string"/>
		<xsd:element name="altre_info" type="xsd:string"/>
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:integer" use="required"/>
	<xsd:attribute name="formato" type="xsd:string" default="no_image"/>
	</xsd:complexType>	
	
	<xsd:complexType name="Tattrezzo">
	<xsd:sequence>
		<xsd:element name="nome" type="xsd:string"/>
		<xsd:element name="tipo" type="xsd:string"/>
		<xsd:element name="prezzo" type="Tprezzo"/>
		<xsd:element name="descrizione" type="xsd:string"/>
		<xsd:element name="dettagli" type="Tdettagli"/>
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:integer" use="required"/>
	<xsd:attribute name="formato" type="xsd:string" default="no_image"/>
	</xsd:complexType>
	
	<xsd:complexType name="Tprezzo">
	<xsd:sequence>
		<xsd:element name="pacchetto" type="Tpacchetto" maxOccurs="unbounded"/>
	</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Tdettagli">
	<xsd:sequence>
		<xsd:element name="dato" type="Tdato" maxOccurs="unbounded"/>
	</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Tpacchetto">
	<xsd:sequence>
		<xsd:element name="valore" type="xsd:string"/>
		<xsd:element name="formato" type="xsd:string"/>
	</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Tdato">
	<xsd:sequence>
		<xsd:element name="nome" type="xsd:string" />
		<xsd:element name="contenuto" type="xsd:string" />
	</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== Cenze94/GGarden/data/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="database.xslt"?>
<p:prodotti xmlns:p="http://www.ggarden.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ggarden.com database.xsd">
	<p:pianta id="00000001" formato="jpg">
		<p:nome>Gerani Birch Double</p:nome>
		<p:nome_scientifico>Geranium Himalayense Plenum</p:nome_scientifico>
		<p:tipo>Piante per aiuole</p:tipo>
		<p:prezzo><p:pacchetto><p:valore>13.95</p:valore><p:formato>per 1 confezione da 3</p:formato></p:pacchetto></p:prezzo>
		<p:descrizione>I Gerani Birch Double (Geranium Himalayense Plenum) sono una varietà resistente al freddo. La pianta sviluppa bellissimi fiori doppi fucsia, larghi 3,5 cm, che contrastano con il fogliame verde. La pianta ha una crescita compatta ed è bellissima nelle aiuole e nei vasi.
		</p:descrizione>
		<p:dettagli>
				<p:dato><p:nome>Mesi di fioritura</p:nome><p:contenuto>Maggio, Giugno, Luglio</p:contenuto></p:dato>
				<p:dato><p:nome>Posizione</p:nome><p:contenuto>Mettere in pieno sole o a mezz'ombra</p:contenuto></p:dato>
				<p:dato><p:nome>Altezza pianta</p:nome><p:contenuto>25-30 cm</p:contenuto></p:dato>
				<p:dato><p:nome>Colore</p:nome><p:contenuto>rosa</p:contenuto></p:dato>
		</p:dettagli>
		<p:piantagione>Se desideri piantare il Geranio Birch Double in vaso, è meglio utilizzare un vaso grande bucherellato sul fondo. Rivesti il fondo del vaso con uno strato di cocci o di idrogranuli. Usa del terriccio fresco e interra la radice del Geranio Birch Double alla giusta profondità giusta, distanziando le piante di circa 15 cm. Riempi col terriccio compattalo e annaffia abbondantemente. Sistema il vaso in un'area soleggiata o parzialmente soleggiata. Se il vaso è poroso foderalo con della plastica per prevenire l'evaporazione dell'acqua ed evitare che il suolo si inaridisca troppo velocemente. Se lo pianti direttamente in giardino, lascia più spazio tra le piante. Grazie alla sua fioritura abbondante e alla sua crescita compatta, il Geranio Birch Double è perfetto nelle aiuole e nelle bordure. Puoi anche creare bellissime combinazioni, abbinandolo con altre piante da aiuola come la Rudbeckia.
		</p:piantagione>
		<p:cura>Il Geranio Birch Double è una pianta perenne che richiede poche cure. Annaffialo regolarmente per non far seccare il terreno intorno alle radici. Taglia completamente i rami secchi per stimolare la formazione di nuovi germogli floreali. Prima dell'inverno la parte aerea della pianta morirà. In inverno proteggi l'apparato radicale distribuendo uno strato di foglie secche sul terreno. Ad inizio primavera fertilizza e taglia tutte le foglie, presto spunteranno i nuovi germogli.
		</p:cura>
		<p:altre_info>Il Geranio Birch Double è compatto e bellissimo. I suoi brillanti fiori fucsia sono rigogliosissimi, doppi e grandi fino a 3,5 cm. Le sue foglie sono molto decorative e ricoprono graziosamente il terreno. In autunno, le foglie della pianta prendono una colorazione rossa autunnale.
		</p:altre_info>
	</p:pianta>
	<p:pianta id="00000002" formato="jpg">
		<p:nome>Edera bicolore</p:nome>
		<p:nome_scientifico>Hedera helix</p:nome_scientifico>
		<p:tipo>Piante da vaso</p:tipo>
		<p:prezzo><p:pacchetto><p:valore>4.95</p:valore><p:formato>cadauno</p:formato></p:pacchetto></p:prezzo>
		<p:descrizione>Eccezionale pianta per purificare l'aria! Questa bellissima edera è molto semplice da coltivare ed estremamente decorativa con il suo fogliame bicolore. L'edera fa parte della famiglia delle Araliacee (famiglia delle edere) ed in natura di solito cresce su alberi e rocce, arrampicandosi fino a 25-30 metri.
		</p:descrizione>
		<p:dettagli>
			<p:dato><p:nome>Posizione</p:nome><p:contenuto>Mettere in pieno sole o a mezz'ombra</p:contenuto></p:dato>
		</p:dettagli>
		<p:piantagione>Riceverai la tua pianta di edera in un vaso da vivaio.
Puoi inserire l'edera direttamente con il vaso da vivaio in una fioriera/vaso più capiente e sistema dei cocci o idrogranuli sul fondo del vaso per favorire il drenaggio dell'acqua.
Oppure puoi travasarla in un altro vaso: anche in questo caso, usa un vaso bucherellato e posiziona degli idrogranuli sul fondo dello stesso. Poi aggiungi del terriccio e sistema la zolla di radice alla giusta profondità, finisci di riempire con terriccio e pressa. Usa un sottovaso per raccogliere l'acqua in eccesso.
		</p:piantagione>
		<p:cura>L'edera è una pianta che non richiede cure particolari ed è facile da coltivare. Annaffiare subito dopo la messa a dimora. Evita di lasciare il terriccio troppo bagnato: meglio farlo asciugare tra un'innaffiatura e l'altra, ciò permette alla pianta di sviluppare un apparato radicale ben ramificato e profondo. Le piante in vaso devono essere irrigate con più frequenza. In inverno necessita di meno irrigazioni che possono essere riprese regolarmente in primavera.
Per mantenere un buon grado di umidità, se necessario, usa un sottovaso riempito con dell'acqua che, evaporando, migliora le condizioni ambientali, non permettere che le radici della pianta siano troppo a contatto con l'acqua. L'edera è una pianta molto robusta che si adatta bene in molti ambienti. La varietà di edera variegata ha bisogno di più luce rispetto alla varietà verde.
Sistema qualcosa che possa permettere all'edera di potersi arrampicare - come ad esempio canne di bambù.
		</p:cura>
		<p:altre_info>Questa edera è originaria delle zone a clima temperato dell'Europa. In natura cresce nelle foreste dove si arrampica lungo gli alberi.
In casa l'edera è spesso coltivata come pianta pensile!
L'edera helix appartiene alla famiglia delle Araliaceae.
Il nome Edera, è un'antichissima denominazione latina, che deriva probabilmente, dalla radice Heud, ovvero prendere o attaccarsi. Inoltre, l'epiteto helix, deriva dal greco helissein che significa arrampicarsi.
		</p:altre_info>
	</p:pianta>
	<p:pianta id="00000003" formato="jpg">
		<p:nome>Origano - sementi</p:nome>
		<p:nome_scientifico>Origanum vulgare</p:nome_scientifico>
		<p:tipo>Piante aromatiche</p:tipo>
		<p:prezzo><p:pacchetto><p:valore>1.95</p:valore><p:formato>a bustina</p:formato></p:pacchetto></p:prezzo>
		<p:descrizione>Il gusto mediterraneo dell'origano è indispensabile nella cucina italiana! Di gran risalto in vaso, puoi coltivarlo anche sul davanzale.
		</p:descrizione>
		<p:dettagli>
			<p:dato><p:nome>Colore</p:nome><p:contenuto>Bianco</p:contenuto></p:dato>
		</p:dettagli>
		<p:piantagione>I semi di origano non necessitano di essere pretrattati. Semina l'origano da aprile a luglio in un posto di ombra parziale, in pieno sole le foglie potrebbero appassire o ingiallire. I semi germinano in 8-15 giorni. Non permettere che le piantine si asciughino.
		</p:piantagione>
		<p:cura>Mantieni il terreno sempre pulito, eliminando costantemente le erbe infestanti e annaffia abbondantemente soprattutto nel caso si verifichino periodi di siccità prolungata. Ciò favorirà una crescita vigorosa delle piante.
L'origano può essere raccolto 6-8 settimane dopo la semina, solitamente nei mesi di aprile-maggio.
		</p:cura>
		<p:altre_info>
		</p:altre_info>
	</p:pianta>
	<p:pianta id="00000004" formato="jpg">
		<p:nome>Rose Porcellana - cespuglio</p:nome>
		<p:nome_scientifico>Rosa sp</p:nome_scientifico>
		<p:tipo>Piante da vaso</p:tipo>
		<p:prezzo><p:pacchetto><p:valore>29.95</p:valore><p:formato>per una confezione da 5 (1 per varietà)</p:formato></p:pacchetto></p:prezzo>
		<p:descrizione>Nessun'altra varietà di rose fiorisce così riccamente come le Rose Porcellana. I folti cespuglietti sono coperti da grappoli di roselline dai colori magnifici. I Rosai Porcellana sono perfetti nelle fioriere sul terrazzo e nelle aiuole in giardino.
		</p:descrizione>
		<p:dettagli>
			<p:dato><p:nome>Fioritura</p:nome><p:contenuto>da giugno a novembre</p:contenuto></p:dato>
			<p:dato><p:nome>Posizione</p:nome><p:contenuto>Mettere in pieno sole o a mezz'ombra</p:contenuto></p:dato>
			<p:dato><p:nome>Colore</p:nome><p:contenuto>misto</p:contenuto></p:dato>
			<p:dato><p:nome>Altezza pianta</p:nome><p:contenuto>30 cm</p:contenuto></p:dato>
			<p:dato><p:nome/><p:contenuto>Ideali da recidere</p:contenuto></p:dato>
		</p:dettagli>
		<p:piantagione>Riceverai le rose porcellana in vaso da vivaio, assicurati che il terreno sia ben bagnato prima di trapiantare le rose, immergendo in un secchio d'acqua per circa 30 minuti. Le rose porcellana crescono bene in un vaso largo, ma anche piantate a terra.
Scava un'ampia buca di piantagione nel terreno sciolto e arricchito con compost e stallatico. Distendi bene le radici delle rose e interrale con il punto d'innesto (la parte rigonfia dalla quale nascono i rami) circa 5 cm sotto il livello del terreno. Riempi la buca col terriccio, premi bene e annaffia abbondantemente. I rosai preferiscono una posizione in pieno sole per fiorire più riccamente. Queste roselline hanno una fioritura incredibile e sviluppano centinaia di rigogliose rose gialle, arancioni, rosa e rosse. Puoi piantare il Rosaio Porcellana nelle aiuole o usarlo come pianta tappezzante.
		</p:piantagione>
		<p:cura>Per stimolare la rifioritura taglia regolarmente i fiori appassiti fino alla prima foglia con cinque foglioline. Fertilizza regolarmente; in inverno distribuisci lo stallatico intorno alla base. A inizio primavera somministra del fertilizzante organico e in luglio del fertilizzante specifico per rose per agevolare la crescita e la fioritura. Per proteggere le sue fragili radici, si raccomanda di rialzare la base della pianta. Pota ad inizio primavera.
Le rose porcellana devono essere potati ogni anno. In marzo potalo mantenendo solo 5 dei rami più vigorosi. Accorcia tutti i rami fino a 3-5 occhi (gemme in riposo). I rosai che ti consegniamo sono già stati potati, dovrai quindi aspettare 12 mesi prima di potarli.
		</p:cura>
